### ISSUE TITLE
new REST endpoint to get clearing request

### ISSUE THREAD

**Issue by deveaud-m** [sw360/sw360python#2]
There is a new REST endpoint to get clearing request info, see  https://github.com/eclipse/sw360/pull/1159

This should be added as `clearingrequest` function in this library.

**Comment by deveaud-m** [comment]
Thanks a lot @tngraf for implementing this so quickly. I'll give it a try now :+1:

**Comment by deveaud-m** [comment]
The new package has not been uploaded to pypi.org yet, would you mind publishing it so I can try the new feature out?

**Comment by tngraf** [comment]
Pubished version 1.0.0 of sw360python :-)
